version: '3.6'
services:
  discordbot:
    container_name: discordbot
    image: ocn-killbot-rust:latest
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./killbot-rust/Dockerfile.rust
    environment:
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}

networks:
  default:
    name: bot-network
    driver: bridge